username = 'postgres'
password = '123'
host = 'localhost'
db_name = 'db_bestiary'

stats_table_name = 'stats'
stats_strength_col_name = 'strength'
stats_strength_col_type = 'integer'
stats_strength_plus_col_name = 'strength_plus'
stats_strength_plus_col_type = 'integer'
stats_physique_col_name = 'physique'
stats_physique_col_type = 'integer'
stats_physique_plus_col_name = 'physique_plus'
stats_physique_plus_col__type = 'integer'
stats_intellect_col_name = 'intellect'
stats_intellect_col__type = 'integer'
stats_intellect_plus_col_name = 'intellect_plus'
stats_intellect_plus_col__type = 'integer'
stats_wisdom_col_name = 'wisdom'
stats_wisdom_col__type = 'integer'
stats_wisdom_plus_col_name = 'wisdom_plus'
stats_wisdom_plus_col__type = 'integer'
stats_charisma_col_name = 'charisma'
stats_charisma_col__type = 'integer'
stats_charisma_plus_col_name = 'charisma_plus'
stats_charisma_plus_col__type = 'integer'

abilities_table_name = 'actions'
abilities_name_col_name = 'info'
abilities_name_col_type = 'text'
abilities_info_col_name = 'buffs'
abilities_info_col_type = 'text'

languages_table_name = 'language'
languages_name_col_name = 'name'
languages_name_col_type = 'text'
languages_info_col_name = 'info'
languages_info_col_type = 'text'

active_actions_table_name = 'active_abilities'
active_actions_name_col_name = 'description'
active_actions_name_col_type = 'text'
active_actions_desc_col_name = 'action_description'
active_actions_desc_col_type = 'text'

speeds_table_name = 'speed'
speeds_entity_col_name = 'entity_id'
speeds_entity_col_type = 'integer'
speeds_type_col_name = 'type'
speeds_type_col_type = 'text'
speeds_value_col_name = 'value'
speeds_value_col_type = 'integer'

armors_table_name = 'armor'
armors_class_col_name = 'armor_class'
armors_class_col_type = 'integer'
armors_type_col_name = 'type'
armors_type_col_type = 'text'
armors_extra_col_name = 'extra_armor'
armors_extra_col_type = 'text'

skills_table_name = 'skills'
skills_name_col_name = 'info'
skills_name_col_type = 'text'
skills_buff_col_name = 'buffs'
skills_buff_col_type = 'integer'

feelings_table_name = 'feelings'
feelings_name_col_name = 'info'
feelings_name_col_type = 'text'
feelings_buff_col_name = 'buffs'
feelings_buff_col_type = 'text'
feelings_radius_col_name = 'redius'
feelings_radius_col_type = 'integer'



